# Generated by Django 3.0 on 2021-03-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20210316_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
